= ADR-024 - Add a simple textual representation type

== Context

On our path to integrating Xtext-based textual DSLs, we need to be able to create simple textual representations for a DSL.

== Decision

We will define a new type of representation.
For representations of that type, the contents are text that is displayed to and editable by the end user.
The representation data will be captured as a string.
The backend will support providing the latest value of the string, and updating the string with a new value.
The frontend will be a Material-UI TextField.
The frontend will update the string value everytime the value in the TextField changes.

We will use this new type of representation for the "State Machine" example DSL from Xtext.
First we will contribute the "State Machine" metamodel in the "Sirius Web Sample Application" (like in e.g. sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/configuration)
Then we will programmatically create a new representation description of that type in the "ODWeb Sample Application" (like in e.g. ocp\backend\odweb-sample-application\src\main\java\fr\obeo\odweb\sample\configuration\RepresentationDescriptionRegistryConfigurer.java)

Use Case / Validation Scenario :
* Create a project
* Create a State Machine model
* Create a new textual representation (and open it)
* Type "Hello World!" in the TextField of the representation
* Close the representation tab
* Open the representation: it contains the "Hello World!" text.

Because we expect our dependency surface to be with LSP/LSP4J, and not with Xtext specifically, we will use "lsp" in our naming scheme.
For now we will create only one backend project in sirius-components, called "sirius-web-lsp".
If needed, we will create the backend Component/Props necessary for the textual representation.

== Future Steps

1) Replace in the frontend the TextWidget with the Monaco Editor

2) Replace in the backend the basic implementation with the State Machine language server generated by Xtext

3) Plug the State Machine language server services (syntax highlighting, auto-completion, validation, etc.) with the Monaco editor.
https://github.com/TypeFox/theia-xtext-sprotty-example may be a good guideline on how to bind LSP services with the Monaco editor.
We also need to make sure that this allows collaboration of some kind on a textual representation. For instance, this could be with the backend notifying the frontend everytime the textual contents change (e.g. to allow GoogleDoc-like collaborative editing).

4) Replace the State Machine metamodel and language server with the ones from SysML v2.

== Status

WIP

* TextField is read-only
* Serialization of the EObject to represent textually is not done yet as it would require adding dependency to Xtext mechanisms

== Consequences

* Textual representations make it easy to put models in invalid states. Synchronizing with other representations may be a challenge. We do not wish to handle that challenge for now and will decide on the issue later / stick to the most straightforward implementation.